package com.github.ayltai.gradle.plugin;

import java.util.ArrayList;
import java.util.List;
import javax.annotation.Nonnull;

import org.gradle.api.tasks.Internal;

public class ApplyTask extends ApplyOrDestroyTask {
    static final String TASK_NAME = "tfApply";

    public ApplyTask() {
        this.setDescription("Apply the changes required to reach the desired state of the configuration, or the pre-determinied set of actions generated by an execution plan");
    }

    @Nonnull
    @Internal
    @Override
    protected List<String> getCommandLineArgs() {
        final List<String> args = new ArrayList<>();
        args.add(this.getCli().getAbsolutePath());
        args.add("apply");
        args.addAll(super.getCommandLineArgs());

        return args;
    }
}
